<a href="https://colab.research.google.com/github/jonkrohn/ML-foundations/blob/master/notebooks/2-linear-algebra-ii.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra II: Matrix Operations

This topic, *Linear Algebra II: Matrix Operations*, builds on the basics of linear algebra. It is essential because these intermediate-level manipulations of tensors lie at the heart of most machine learning approaches and are especially predominant in deep learning. 

Through the measured exposition of theory paired with interactive examples, you’ll develop an understanding of how linear algebra is used to solve for unknown values in high-dimensional spaces as well as to reduce the dimensionality of complex spaces. The content covered in this topic is itself foundational for several other topics in the *Machine Learning Foundations* series, especially *Probability & Information Theory* and *Optimization*. 

Over the course of studying this topic, you'll: 

* Develop a geometric intuition of what’s going on beneath the hood of machine learning algorithms, including those used for deep learning. 
* Be able to more intimately grasp the details of machine learning papers as well as all of the other subjects that underlie ML, including calculus, statistics, and optimization algorithms. 
* Reduce the dimensionalty of complex spaces down to their most informative elements with techniques such as eigendecomposition, singular value decomposition, and principal components analysis.

**Note that this Jupyter notebook is not intended to stand alone. It is the companion code to a lecture or to videos from Jon Krohn's [Machine Learning Foundations](https://github.com/jonkrohn/ML-foundations) series, which offer detail on the following:**

*Review of Tensor Properties*

* Tensors
* Basic Tensor Operations
* Multiplying Matrices and Vectors
* Identity and Inverse Matrices
* Linear Dependence and Span
* Norms
* The Relationship of Norms to Objective Functions
* Special Matrices: Diagonal, Symmetric, and Orthogonal

*Segment 2: Eigendecomposition*

* Eigenvectors
* Eigenvalues
* Matrix Decomposition 

*Segment 3: Matrix Properties & Operations for Machine Learning*

* Singular Value Decomposition (SVD)
* The Moore-Penrose Pseudoinverse
* The Trace Operator
* The Determinant
* Principal Components Analysis (PCA): A Simple Machine Learning Algorithm
* Resources for Further Study of Linear Algebra

## Segment 1: Review of Tensor Properties

In [1]:
import torch

### Vector Transposition

In [2]:
x = torch.tensor([25, 2, 5])
x

tensor([25,  2,  5])

In [3]:
x.T

tensor([25,  2,  5])

In [6]:
x.view(3, 1) # "view" because we're changing output but not the way x is stored in memory

tensor([[25],
        [ 2],
        [ 5]])

**Return to slides here.**

## $L^2$ Norm

In [7]:
x

tensor([25,  2,  5])

In [8]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [12]:
# the following line of code will fail because torch.norm() requires input to be float not integer
# torch.norm(x)

In [10]:
torch.norm(torch.tensor([25, 2, 5.]))

tensor(25.5734)

So, if units in this 3-dimensional vector space are meters, then the vector $x$ has a length of 25.6m

**Return to slides here.**

### Matrices

In [13]:
X = torch.tensor([[25, 2], [5, 26], [3, 7]])
X

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [14]:
X.shape

torch.Size([3, 2])

In [15]:
X[:,0]

tensor([25,  5,  3])

In [16]:
X[1,:]

tensor([ 5, 26])

In [17]:
X[0:2, 0:2]

tensor([[25,  2],
        [ 5, 26]])

**Return to slides here.**

### Matrix Transposition

In [18]:
X

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [19]:
X.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

**Return to slides here.**

### Matrix Multiplication

Scalars are applied to each element of matrix:

In [20]:
X*3

tensor([[75,  6],
        [15, 78],
        [ 9, 21]])

In [21]:
X*3+3

tensor([[78,  9],
        [18, 81],
        [12, 24]])

Using the multiplication operator on two tensors of the same size in PyTorch (or Numpy or TensorFlow) applies element-wise operations. This is the **Hadamard product** (denoted by the $\odot$ operator, e.g., $A \odot B$) *not* **matrix multiplication**: 

In [22]:
A = torch.tensor([[0, 1], [1, 2], [9, 10]])
A

tensor([[ 0,  1],
        [ 1,  2],
        [ 9, 10]])

In [23]:
X

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [24]:
X * A

tensor([[ 0,  2],
        [ 5, 52],
        [27, 70]])

Matrix multiplication with a vector: 

In [25]:
b = torch.tensor([1, 2])
b

tensor([1, 2])

In [27]:
torch.matmul(A, b)

tensor([ 2,  5, 29])

Matrix multiplication with two matrices:

In [28]:
A

tensor([[ 0,  1],
        [ 1,  2],
        [ 9, 10]])

In [29]:
B = torch.tensor([[1, 9], [2, 0]])
B

tensor([[1, 9],
        [2, 0]])

In [30]:
torch.matmul(A, B) # note first column is same as Ab

tensor([[ 2,  0],
        [ 5,  9],
        [29, 81]])