In [33]:
m = torch.tensor([0.9]).requires_grad_()

In [34]:
b = torch.tensor([0.1]).requires_grad_()

In [35]:
def mse(my_yhat, my_y): 
    sigma = torch.sum((my_yhat - my_y)**2)
    return sigma/len(my_y)

In [36]:
yhats = regression(xs, m, b)
yhats

tensor([0.1000, 1.0000, 1.9000, 2.8000, 3.7000, 4.6000, 5.5000, 6.4000],
       grad_fn=<AddBackward0>)

In [37]:
C = mse(yhats, ys)
C

tensor(19.6755, grad_fn=<DivBackward0>)

In [38]:
C.backward()

In [39]:
m.grad

tensor([36.3050])

In [48]:
2*1/len(ys)*torch.sum((yhats - ys)*xs)

tensor(36.3050, grad_fn=<MulBackward0>)

In [40]:
b.grad

tensor([6.2650])

In [47]:
2*1/len(ys)*torch.sum(yhats - ys)

tensor(6.2650, grad_fn=<MulBackward0>)