In [1]:
import torch
import matplotlib.pyplot as plt

In [2]:
xs = torch.tensor([0, 1, 2, 3, 4, 5, 6, 7.])

In [3]:
ys = torch.tensor([1.86, 1.31, .62, .33, .09, -.67, -1.23, -1.37])

In [4]:
m = torch.tensor([0.9]).requires_grad_()

In [5]:
b = torch.tensor([0.1]).requires_grad_()

In [6]:
def regression(my_x, my_m, my_b):
    return my_x*my_m + my_b

In [7]:
def squared_error(my_yhat, my_y):
    return (my_yhat - my_y)**2

In [8]:
i = 7

In [9]:
x = xs[i]
y = ys[i]

In [10]:
yhat = regression(x, m, b)
yhat

tensor([6.4000], grad_fn=<AddBackward0>)

In [11]:
C = squared_error(yhat, y)
C

tensor([60.3729], grad_fn=<PowBackward0>)

In [12]:
C.backward()

In [13]:
m.grad

tensor([108.7800])

In [14]:
b.grad

tensor([15.5400])

From the slides: $$ \frac{\partial C}{\partial m} = 2x(\hat{y} - y) $$

In [25]:
2*x*(yhat - y)

tensor([108.7800], grad_fn=<MulBackward0>)

$$ \frac{\partial C}{\partial b} = 2(\hat{y}-y) $$

In [16]:
2*(yhat-y)

tensor([15.5400], grad_fn=<MulBackward0>)

$\nabla C = \left[ \frac{\partial{C}}{\partial{p_1}}, \frac{\partial{C}}{\partial{p_2}}, \cdots, \frac{\partial{C}}{\partial{p_n}} \right]^T $

$\nabla C = \left[ \frac{\partial{C}}{\partial{m}}, \frac{\partial{C}}{\partial{b}} \right]^T $

In [22]:
C_grad = torch.tensor([m.grad.item(), b.grad.item()]).T
C_grad

tensor([108.7800,  15.5400])